package csu.mrc.ivcc.mdss.geo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AllowedIn.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AllowedInQueryDTO extends com.terraframe.mojo.business.RelationshipQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236612272344L;

  protected AllowedInQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.geo.AllowedInDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.geo.AllowedInDTO>)super.getResultSet();
}
}
