package csu.mrc.ivcc.mdss.geo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GeoEntityDefinition.java
 *
 * @author Autogenerated by TerraFrame
 */
public class GeoEntityDefinitionQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236612272024L;

  protected GeoEntityDefinitionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.geo.GeoEntityDefinitionDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.geo.GeoEntityDefinitionDTO>)super.getResultSet();
}
}
