import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.ifomis.org/bfo/1.1/span#ProcessAggregate
 *
 * @version generated on Mon Jan 19 17:55:02 MST 2009
 */
public interface ProcessAggregate extends ProcessualEntity {
}
