/**
 * Generated by the EMFGenerator from the Protege OWL Plugin (http://protege.stanford.edu).
 * Source OWL Class: http://www.ifomis.org/bfo/1.1/span#ProcessualContext
 * @version generated on Mon Jan 19 17:52:31 MST 2009
 * @model
 */
public interface span_ProcessualContext extends span_ProcessualEntity {
}
