package csu.mrc.ivcc.mdss.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to BiochemicalMethodology.java
 *
 * @author Autogenerated by TerraFrame
 */
public class BiochemicalMethodologyQueryDTO extends csu.mrc.ivcc.mdss.mo.AbstractTermQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236803168584L;

  protected BiochemicalMethodologyQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.mo.BiochemicalMethodologyDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.mo.BiochemicalMethodologyDTO>)super.getResultSet();
}
}
