package csu.mrc.ivcc.mdss.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to CollectionMethod.java
 *
 * @author Autogenerated by TerraFrame
 */
public class CollectionMethodQueryDTO extends csu.mrc.ivcc.mdss.mo.AbstractTermQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237219384521L;

  protected CollectionMethodQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.mo.CollectionMethodDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.mo.CollectionMethodDTO>)super.getResultSet();
}
}
