package csu.mrc.ivcc.mdss.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Insecticide.java
 *
 * @author Autogenerated by TerraFrame
 */
public class InsecticideQueryDTO extends csu.mrc.ivcc.mdss.mo.AbstractTermQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236382974809L;

  protected InsecticideQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.mo.InsecticideDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.mo.InsecticideDTO>)super.getResultSet();
}
}
