package dss.vector.solutions.surveillance;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AggregatedAgeGroup.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AggregatedAgeGroupQueryDTO extends com.terraframe.mojo.business.BusinessQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239517541332L;

  protected AggregatedAgeGroupQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.surveillance.AggregatedAgeGroupDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.surveillance.AggregatedAgeGroupDTO>)super.getResultSet();
}
}
