package dss.vector.solutions.surveillance;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DiagnosticGrid.java
 *
 * @author Autogenerated by TerraFrame
 */
public class DiagnosticGridQueryDTO extends dss.vector.solutions.surveillance.AbstractGridQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239670219356L;

  protected DiagnosticGridQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.surveillance.DiagnosticGridDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.surveillance.DiagnosticGridDTO>)super.getResultSet();
}
}
