package dss.vector.solutions.surveillance;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PeriodTypeMaster.java
 *
 * @author Autogenerated by TerraFrame
 */
public class PeriodTypeMasterQueryDTO extends com.terraframe.mojo.system.EnumerationMasterQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239517582015L;

  protected PeriodTypeMasterQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.surveillance.PeriodTypeMasterDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.surveillance.PeriodTypeMasterDTO>)super.getResultSet();
}
}
