package csu.mrc.ivcc.mdss.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Generation.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class GenerationBase extends csu.mrc.ivcc.mdss.mo.AbstractTerm implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "csu.mrc.ivcc.mdss.mo.Generation";
  private static final long serialVersionUID = 1236803167148L;
  
  public GenerationBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static GenerationQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    GenerationQuery query = new GenerationQuery(new com.terraframe.mojo.query.QueryFactory());
    com.terraframe.mojo.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static Generation get(String id)
  {
    return (Generation) com.terraframe.mojo.business.Business.get(id);
  }
  
  public static csu.mrc.ivcc.mdss.mo.Generation[] getAll()
  {
    return null;
  }
  
  public static Generation lock(java.lang.String id)
  {
    Generation _instance = Generation.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static Generation unlock(java.lang.String id)
  {
    Generation _instance = Generation.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
