package csu.mrc.ivcc.mdss.entomology.assay.molecular;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AcHETestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AcHETestResultQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.molecular.MolecularAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237219388476L;

  protected AcHETestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.molecular.AcHETestResultDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.molecular.AcHETestResultDTO>)super.getResultSet();
}
}
