package csu.mrc.ivcc.mdss.entomology.assay.molecular;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to EKDRTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class EKDRTestResultQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.molecular.MolecularAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236360379016L;

  protected EKDRTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.molecular.EKDRTestResultDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.molecular.EKDRTestResultDTO>)super.getResultSet();
}
}
