package dss.vector.solutions.entomology.assay.biochemical;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GSTTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class GSTTestResultBase extends dss.vector.solutions.entomology.assay.biochemical.BiochemicalAssayTestResult implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "dss.vector.solutions.entomology.assay.biochemical.GSTTestResult";
  public static java.lang.String TESTRESULT = "testResult";
  private static final long serialVersionUID = 1237240899754L;
  
  public GSTTestResultBase()
  {
    super();
  }
  
  public Integer getTestResult()
  {
    return com.terraframe.mojo.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(TESTRESULT));
  }
  
  public void validateTestResult()
  {
    this.validateAttribute(TESTRESULT);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getTestResultMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.entomology.assay.biochemical.GSTTestResult.CLASS);
    return mdClassIF.definesAttribute(TESTRESULT);
  }
  
  public void setTestResult(Integer value)
  {
    if(value == null)
    {
      setValue(TESTRESULT, "");
    }
    else
    {
      setValue(TESTRESULT, java.lang.Integer.toString(value));
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static GSTTestResultQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    GSTTestResultQuery query = new GSTTestResultQuery(new com.terraframe.mojo.query.QueryFactory());
    com.terraframe.mojo.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static GSTTestResult get(String id)
  {
    return (GSTTestResult) com.terraframe.mojo.business.Business.get(id);
  }
  
  public static GSTTestResult lock(java.lang.String id)
  {
    GSTTestResult _instance = GSTTestResult.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static GSTTestResult unlock(java.lang.String id)
  {
    GSTTestResult _instance = GSTTestResult.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
