package dss.vector.solutions.entomology.assay.molecular;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to WKDRTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class WKDRTestResultQueryDTO extends dss.vector.solutions.entomology.assay.molecular.TargetSiteAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239517515635L;

  protected WKDRTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.assay.molecular.WKDRTestResultDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.assay.molecular.WKDRTestResultDTO>)super.getResultSet();
}
}
