package dss.vector.solutions.surveillance;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DistinctAgeGroupException.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class DistinctAgeGroupExceptionBase extends com.terraframe.mojo.business.SmartException implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "dss.vector.solutions.surveillance.DistinctAgeGroupException";
  public static java.lang.String ENDAGE = "endAge";
  public static java.lang.String ID = "id";
  public static java.lang.String STARTAGE = "startAge";
  private static final long serialVersionUID = 1239517547465L;
  
  public DistinctAgeGroupExceptionBase()
  {
    super();
  }
  
  public DistinctAgeGroupExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public DistinctAgeGroupExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public DistinctAgeGroupExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public Integer getEndAge()
  {
    return com.terraframe.mojo.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(ENDAGE));
  }
  
  public void validateEndAge()
  {
    this.validateAttribute(ENDAGE);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getEndAgeMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.surveillance.DistinctAgeGroupException.CLASS);
    return mdClassIF.definesAttribute(ENDAGE);
  }
  
  public void setEndAge(Integer value)
  {
    if(value == null)
    {
      setValue(ENDAGE, "");
    }
    else
    {
      setValue(ENDAGE, java.lang.Integer.toString(value));
    }
  }
  
  public String getId()
  {
    return getValue(ID);
  }
  
  public void validateId()
  {
    this.validateAttribute(ID);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getIdMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.surveillance.DistinctAgeGroupException.CLASS);
    return mdClassIF.definesAttribute(ID);
  }
  
  public Integer getStartAge()
  {
    return com.terraframe.mojo.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(STARTAGE));
  }
  
  public void validateStartAge()
  {
    this.validateAttribute(STARTAGE);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getStartAgeMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.surveillance.DistinctAgeGroupException.CLASS);
    return mdClassIF.definesAttribute(STARTAGE);
  }
  
  public void setStartAge(Integer value)
  {
    if(value == null)
    {
      setValue(STARTAGE, "");
    }
    else
    {
      setValue(STARTAGE, java.lang.Integer.toString(value));
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    try
    {
      java.lang.String message = com.terraframe.mojo.util.LocalizeUtil.getTemplate("dss.vector.solutions.surveillance.DistinctAgeGroupException", locale);
      
      message = replace(message, "{endAge}", this.getEndAge());
      message = replace(message, "{id}", this.getId());
      message = replace(message, "{startAge}", this.getStartAge());
      
      return message;
    }
    catch (java.io.IOException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (org.xml.sax.SAXException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (javax.xml.parsers.ParserConfigurationException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (com.terraframe.mojo.util.LocalizeException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
  }
  
}
