package csu.mrc.ivcc.mdss.entomology.assay.biochemical;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GSTTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class GSTTestResultQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.biochemical.BiochemicalAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237219376768L;

  protected GSTTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.biochemical.GSTTestResultDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.biochemical.GSTTestResultDTO>)super.getResultSet();
}
}
