package dss.vector.solutions.geo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GeoHierarchyView.java
 *
 * @author Autogenerated by TerraFrame
 */
public class GeoHierarchyViewQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239670223253L;

  protected GeoHierarchyViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.geo.GeoHierarchyViewDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.geo.GeoHierarchyViewDTO>)super.getResultSet();
}
}
