package dss.vector.solutions;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Property.java
 *
 * @author Autogenerated by TerraFrame
 */
public class PropertyQueryDTO extends com.terraframe.mojo.business.BusinessQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237240925016L;

  protected PropertyQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.PropertyDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.PropertyDTO>)super.getResultSet();
}
}
