package dss.vector.solutions.geo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SpatialTypeDefinedException.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class SpatialTypeDefinedExceptionBase extends com.terraframe.mojo.business.SmartException implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "dss.vector.solutions.geo.SpatialTypeDefinedException";
  public static java.lang.String ID = "id";
  public static java.lang.String ISAPARENTLABEL = "isAParentLabel";
  public static java.lang.String SPATIALLABEL = "spatialLabel";
  private static final long serialVersionUID = 1239658589241L;
  
  public SpatialTypeDefinedExceptionBase()
  {
    super();
  }
  
  public SpatialTypeDefinedExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public SpatialTypeDefinedExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public SpatialTypeDefinedExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getId()
  {
    return getValue(ID);
  }
  
  public void validateId()
  {
    this.validateAttribute(ID);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getIdMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.geo.SpatialTypeDefinedException.CLASS);
    return mdClassIF.definesAttribute(ID);
  }
  
  public String getIsAParentLabel()
  {
    return getValue(ISAPARENTLABEL);
  }
  
  public void validateIsAParentLabel()
  {
    this.validateAttribute(ISAPARENTLABEL);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getIsAParentLabelMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.geo.SpatialTypeDefinedException.CLASS);
    return mdClassIF.definesAttribute(ISAPARENTLABEL);
  }
  
  public void setIsAParentLabel(String value)
  {
    if(value == null)
    {
      setValue(ISAPARENTLABEL, "");
    }
    else
    {
      setValue(ISAPARENTLABEL, value);
    }
  }
  
  public String getSpatialLabel()
  {
    return getValue(SPATIALLABEL);
  }
  
  public void validateSpatialLabel()
  {
    this.validateAttribute(SPATIALLABEL);
  }
  
  public static com.terraframe.mojo.dataaccess.MdAttributeDAOIF getSpatialLabelMd()
  {
    com.terraframe.mojo.dataaccess.MdClassDAOIF mdClassIF = com.terraframe.mojo.dataaccess.metadata.MdClassDAO.getMdClassDAO(dss.vector.solutions.geo.SpatialTypeDefinedException.CLASS);
    return mdClassIF.definesAttribute(SPATIALLABEL);
  }
  
  public void setSpatialLabel(String value)
  {
    if(value == null)
    {
      setValue(SPATIALLABEL, "");
    }
    else
    {
      setValue(SPATIALLABEL, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    try
    {
      java.lang.String message = com.terraframe.mojo.util.LocalizeUtil.getTemplate("dss.vector.solutions.geo.SpatialTypeDefinedException", locale);
      
      message = replace(message, "{id}", this.getId());
      message = replace(message, "{isAParentLabel}", this.getIsAParentLabel());
      message = replace(message, "{spatialLabel}", this.getSpatialLabel());
      
      return message;
    }
    catch (java.io.IOException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (org.xml.sax.SAXException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (javax.xml.parsers.ParserConfigurationException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
    catch (com.terraframe.mojo.util.LocalizeException e)
    {
      throw new com.terraframe.mojo.dataaccess.io.XMLException(e.getLocalizedMessage());
    }
  }
  
}
