package dss.vector.solutions.geo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SpatialMaster.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class SpatialMasterBase extends com.terraframe.mojo.system.EnumerationMaster implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "dss.vector.solutions.geo.SpatialMaster";
  private static final long serialVersionUID = 1239572491237L;
  
  public SpatialMasterBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static SpatialMasterQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    SpatialMasterQuery query = new SpatialMasterQuery(new com.terraframe.mojo.query.QueryFactory());
    com.terraframe.mojo.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static SpatialMaster get(String id)
  {
    return (SpatialMaster) com.terraframe.mojo.business.Business.get(id);
  }
  
  public static SpatialMaster getEnumeration(String enumName)
  {
    return (SpatialMaster) com.terraframe.mojo.business.Business.getEnumeration("dss.vector.solutions.geo.SpatialMaster",enumName);
  }
  
  public static SpatialMaster lock(java.lang.String id)
  {
    SpatialMaster _instance = SpatialMaster.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static SpatialMaster unlock(java.lang.String id)
  {
    SpatialMaster _instance = SpatialMaster.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
