package dss.vector.solutions.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MosquitoCollection.java
 *
 * @author Autogenerated by TerraFrame
 */
public class MosquitoCollectionQueryDTO extends dss.vector.solutions.entomology.ConcreteMosquitoCollectionQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237240904083L;

  protected MosquitoCollectionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.MosquitoCollectionDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.MosquitoCollectionDTO>)super.getResultSet();
}
}
