package dss.vector.solutions.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MosquitoView.java
 *
 * @author Autogenerated by TerraFrame
 */
public class MosquitoViewQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239670243993L;

  protected MosquitoViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.MosquitoViewDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.MosquitoViewDTO>)super.getResultSet();
}
}
