package dss.vector.solutions.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to TrueSpecieEntity.java
 *
 * @author Autogenerated by TerraFrame
 */
public class TrueSpecieEntityQueryDTO extends com.terraframe.mojo.business.BusinessQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237240910950L;

  protected TrueSpecieEntityQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.TrueSpecieEntityDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.TrueSpecieEntityDTO>)super.getResultSet();
}
}
