package impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.ifomis.org/bfo/1.1/span#SpatiotemporalRegion
 *
 * @version generated on Mon Jan 19 17:55:02 MST 2009
 */
public class DefaultSpatiotemporalRegion extends DefaultOccurrent
         implements SpatiotemporalRegion {

    public DefaultSpatiotemporalRegion(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultSpatiotemporalRegion() {
    }
}
