package csu.mrc.ivcc.mdss.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MosquitoCollectionPointView.java
 *
 * @author Autogenerated by TerraFrame
 */
public class MosquitoCollectionPointViewQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236360379077L;

  protected MosquitoCollectionPointViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointViewDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointViewDTO>)super.getResultSet();
}
}
