package csu.mrc.ivcc.mdss.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to UninterestingSpecieGroup.java
 *
 * @author Autogenerated by TerraFrame
 */
public class UninterestingSpecieGroupQueryDTO extends csu.mrc.ivcc.mdss.entomology.TrueSpecieEntityQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236803157844L;

  protected UninterestingSpecieGroupQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.UninterestingSpecieGroupDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.UninterestingSpecieGroupDTO>)super.getResultSet();
}
}
