package dss.vector.solutions.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to LarvaeAge.java
 *
 * @author Autogenerated by TerraFrame
 */
public class LarvaeAgeQueryDTO extends dss.vector.solutions.mo.AbstractTermQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237423123275L;

  protected LarvaeAgeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.mo.LarvaeAgeDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.mo.LarvaeAgeDTO>)super.getResultSet();
}
}
