package dss.vector.solutions.mo;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ResistanceMethodology.java
 *
 * @author Autogenerated by TerraFrame
 */
public class ResistanceMethodologyQueryDTO extends dss.vector.solutions.mo.AbstractTermQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1238826363685L;

  protected ResistanceMethodologyQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.mo.ResistanceMethodologyDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.mo.ResistanceMethodologyDTO>)super.getResultSet();
}
}
