package dss.vector.solutions.general;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Insecticide.java
 *
 * @author Autogenerated by TerraFrame
 */
public class InsecticideQueryDTO extends com.terraframe.mojo.business.BusinessQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1238826373276L;

  protected InsecticideQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.general.InsecticideDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.general.InsecticideDTO>)super.getResultSet();
}
}
