package dss.vector.solutions.general;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to KnockDownTimeProperty.java
 *
 * @author Autogenerated by TerraFrame
 */
public class KnockDownTimePropertyQueryDTO extends com.terraframe.mojo.business.BusinessQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239572446855L;

  protected KnockDownTimePropertyQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.general.KnockDownTimePropertyDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.general.KnockDownTimePropertyDTO>)super.getResultSet();
}
}
