package csu.mrc.ivcc.mdss.export.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MosquitoCollectionView.java
 *
 * @author Autogenerated by TerraFrame
 */
public class MosquitoCollectionViewQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236982466915L;

  protected MosquitoCollectionViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.export.entomology.MosquitoCollectionViewDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.export.entomology.MosquitoCollectionViewDTO>)super.getResultSet();
}
}
