package dss.vector.solutions.entomology.assay.biochemical;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AcHETestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AcHETestResultQueryDTO extends dss.vector.solutions.entomology.assay.biochemical.BiochemicalAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237423105479L;

  protected AcHETestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.AcHETestResultDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.AcHETestResultDTO>)super.getResultSet();
}
}
