package dss.vector.solutions.entomology.assay.biochemical;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GSTDCNBTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class GSTDCNBTestResultQueryDTO extends dss.vector.solutions.entomology.assay.biochemical.MetabolicAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1238027453711L;

  protected GSTDCNBTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.GSTDCNBTestResultDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.GSTDCNBTestResultDTO>)super.getResultSet();
}
}
