package dss.vector.solutions.entomology.assay.biochemical;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MetabolicAssayTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class MetabolicAssayTestResultQueryDTO extends dss.vector.solutions.entomology.assay.AssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239075035249L;

  protected MetabolicAssayTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.MetabolicAssayTestResultDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.assay.biochemical.MetabolicAssayTestResultDTO>)super.getResultSet();
}
}
