package dss.vector.solutions.entomology.assay;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DDATestIntervalView.java
 *
 * @author Autogenerated by TerraFrame
 */
public class DDATestIntervalViewQueryDTO extends com.terraframe.mojo.business.ViewQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1237423100284L;

  protected DDATestIntervalViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends dss.vector.solutions.entomology.assay.DDATestIntervalViewDTO> getResultSet()
{
  return (java.util.List<? extends dss.vector.solutions.entomology.assay.DDATestIntervalViewDTO>)super.getResultSet();
}
}
