<%@ taglib uri="/WEB-INF/tlds/mojoLib.tld" prefix="mjl"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<mjl:messages>
  <mjl:message />
</mjl:messages>
<mjl:form name="dss.vector.solutions.irs.ResourceTarget.form.name" id="dss.vector.solutions.irs.ResourceTarget.form.id" method="POST">
  <mjl:input value="${item.id}" type="hidden" param="id" />
  <dl>
    <dt>
      <label>
        ${item.targetYearMd.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.targetYear}
    </dd>
    <dt>
      <label>
        ${item.target_0Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_0}
    </dd>
    <dt>
      <label>
        ${item.target_1Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_1}
    </dd>
    <dt>
      <label>
        ${item.target_10Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_10}
    </dd>
    <dt>
      <label>
        ${item.target_11Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_11}
    </dd>
    <dt>
      <label>
        ${item.target_12Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_12}
    </dd>
    <dt>
      <label>
        ${item.target_13Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_13}
    </dd>
    <dt>
      <label>
        ${item.target_14Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_14}
    </dd>
    <dt>
      <label>
        ${item.target_15Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_15}
    </dd>
    <dt>
      <label>
        ${item.target_16Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_16}
    </dd>
    <dt>
      <label>
        ${item.target_17Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_17}
    </dd>
    <dt>
      <label>
        ${item.target_18Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_18}
    </dd>
    <dt>
      <label>
        ${item.target_19Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_19}
    </dd>
    <dt>
      <label>
        ${item.target_2Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_2}
    </dd>
    <dt>
      <label>
        ${item.target_20Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_20}
    </dd>
    <dt>
      <label>
        ${item.target_21Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_21}
    </dd>
    <dt>
      <label>
        ${item.target_22Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_22}
    </dd>
    <dt>
      <label>
        ${item.target_23Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_23}
    </dd>
    <dt>
      <label>
        ${item.target_24Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_24}
    </dd>
    <dt>
      <label>
        ${item.target_25Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_25}
    </dd>
    <dt>
      <label>
        ${item.target_26Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_26}
    </dd>
    <dt>
      <label>
        ${item.target_27Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_27}
    </dd>
    <dt>
      <label>
        ${item.target_28Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_28}
    </dd>
    <dt>
      <label>
        ${item.target_29Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_29}
    </dd>
    <dt>
      <label>
        ${item.target_3Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_3}
    </dd>
    <dt>
      <label>
        ${item.target_30Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_30}
    </dd>
    <dt>
      <label>
        ${item.target_31Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_31}
    </dd>
    <dt>
      <label>
        ${item.target_32Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_32}
    </dd>
    <dt>
      <label>
        ${item.target_33Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_33}
    </dd>
    <dt>
      <label>
        ${item.target_34Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_34}
    </dd>
    <dt>
      <label>
        ${item.target_35Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_35}
    </dd>
    <dt>
      <label>
        ${item.target_36Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_36}
    </dd>
    <dt>
      <label>
        ${item.target_37Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_37}
    </dd>
    <dt>
      <label>
        ${item.target_38Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_38}
    </dd>
    <dt>
      <label>
        ${item.target_39Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_39}
    </dd>
    <dt>
      <label>
        ${item.target_4Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_4}
    </dd>
    <dt>
      <label>
        ${item.target_40Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_40}
    </dd>
    <dt>
      <label>
        ${item.target_41Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_41}
    </dd>
    <dt>
      <label>
        ${item.target_42Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_42}
    </dd>
    <dt>
      <label>
        ${item.target_43Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_43}
    </dd>
    <dt>
      <label>
        ${item.target_44Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_44}
    </dd>
    <dt>
      <label>
        ${item.target_45Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_45}
    </dd>
    <dt>
      <label>
        ${item.target_46Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_46}
    </dd>
    <dt>
      <label>
        ${item.target_47Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_47}
    </dd>
    <dt>
      <label>
        ${item.target_48Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_48}
    </dd>
    <dt>
      <label>
        ${item.target_49Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_49}
    </dd>
    <dt>
      <label>
        ${item.target_5Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_5}
    </dd>
    <dt>
      <label>
        ${item.target_50Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_50}
    </dd>
    <dt>
      <label>
        ${item.target_51Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_51}
    </dd>
    <dt>
      <label>
        ${item.target_52Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_52}
    </dd>
    <dt>
      <label>
        ${item.target_6Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_6}
    </dd>
    <dt>
      <label>
        ${item.target_7Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_7}
    </dd>
    <dt>
      <label>
        ${item.target_8Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_8}
    </dd>
    <dt>
      <label>
        ${item.target_9Md.displayLabel}
      </label>
    </dt>
    <dd>
      ${item.target_9}
    </dd>
    <dt>
      <label>
        ${item.targeterMd.displayLabel}
      </label>
    </dt>
    <dd>
      <mjl:commandLink display="${item.targeter.keyName}" action="dss.vector.solutions.irs.TargeterController.view.mojo" name="dss.vector.solutions.irs.Targeter.form.view.link">
        <mjl:property value="${item.targeter.id}" name="id" />
      </mjl:commandLink>
    </dd>
  </dl>
  <mjl:command value="Edit" action="dss.vector.solutions.irs.ResourceTargetController.edit.mojo" name="dss.vector.solutions.irs.ResourceTarget.form.edit.button" />
  <br />
</mjl:form>
<dl>
</dl>
<mjl:commandLink display="View All" action="dss.vector.solutions.irs.ResourceTargetController.viewAll.mojo" name="dss.vector.solutions.irs.ResourceTarget.viewAll.link" />
