package csu.mrc.ivcc.mdss.entomology.assay.infectivity;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PMalariaeTestResult.java
 *
 * @author Autogenerated by TerraFrame
 */
public class PMalariaeTestResultQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.infectivity.InfectivityAssayTestResultQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236982479258L;

  protected PMalariaeTestResultQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.infectivity.PMalariaeTestResultDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.infectivity.PMalariaeTestResultDTO>)super.getResultSet();
}
}
