package csu.mrc.ivcc.mdss.entomology.assay;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AdultAgeRange.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AdultAgeRangeQueryDTO extends com.terraframe.mojo.business.StructQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236982483317L;

  protected AdultAgeRangeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.AdultAgeRangeDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.AdultAgeRangeDTO>)super.getResultSet();
}
}
