package csu.mrc.ivcc.mdss.entomology.assay;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AdultAssay.java
 *
 * @author Autogenerated by TerraFrame
 */
public class AdultAssayQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.AbstractAssayQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236360376627L;

  protected AdultAssayQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.AdultAssayDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.AdultAssayDTO>)super.getResultSet();
}
}
