package csu.mrc.ivcc.mdss.entomology.assay;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DiscriminatingDoseAssay.java
 *
 * @author Autogenerated by TerraFrame
 */
public class DiscriminatingDoseAssayQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.CollectionAssayQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236982463329L;

  protected DiscriminatingDoseAssayQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.DiscriminatingDoseAssayDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.DiscriminatingDoseAssayDTO>)super.getResultSet();
}
}
