package csu.mrc.ivcc.mdss.entomology.assay;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to InsecticideAssay.java
 *
 * @author Autogenerated by TerraFrame
 */
public class InsecticideAssayQueryDTO extends csu.mrc.ivcc.mdss.entomology.assay.AdultAssayQueryDTO
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236807469951L;

  protected InsecticideAssayQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.InsecticideAssayDTO> getResultSet()
{
  return (java.util.List<? extends csu.mrc.ivcc.mdss.entomology.assay.InsecticideAssayDTO>)super.getResultSet();
}
}
