package dss.vector.solutions.surveillance;

/**
 *
 * @author Autogenerated by TerraFrame
 */
public class AggregatedCaseViewQuery extends dss.vector.solutions.surveillance.AggregatedCaseViewQueryBase  implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1239135495824L;

  public AggregatedCaseViewQuery(com.terraframe.mojo.query.QueryFactory queryFactory)
  {
    super(queryFactory);
    this.buildQuery(new DefaultAggregatedCaseViewBuilder(queryFactory));
  }

  public AggregatedCaseViewQuery(com.terraframe.mojo.query.QueryFactory queryFactory, com.terraframe.mojo.query.ViewQueryBuilder viewQueryBuilder)
  {
    super(queryFactory, viewQueryBuilder);
  }

  class DefaultAggregatedCaseViewBuilder extends com.terraframe.mojo.query.ViewQueryBuilder implements com.terraframe.mojo.generation.loader.Reloadable
  {
    public DefaultAggregatedCaseViewBuilder(com.terraframe.mojo.query.QueryFactory queryFactory)
    {
      super(queryFactory);
    }

    protected AggregatedCaseViewQuery getViewQuery()
    {
      return (AggregatedCaseViewQuery)super.getViewQuery();
    }

    /**
     * build the select clause
     */
    protected void buildSelectClause()
    {
      AggregatedCaseViewQuery viewQuery = this.getViewQuery();

      String errMsg = "buildSelectClause() method in class DefaultAggregatedCaseViewBuilder needs to be overwritten.";
      throw new com.terraframe.mojo.query.QueryException(errMsg);
    }

    /**
     * Implement only if additional join criteria is required.
     */
    protected void buildWhereClause()
    {

    }

  }
}
