package csu.mrc.ivcc.mdss.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MosquitoCollectionPointView.java
 *
 * @author Autogenerated by TerraFrame
 */
public  abstract  class MosquitoCollectionPointViewQueryBase extends com.terraframe.mojo.query.GeneratedViewQuery
 implements com.terraframe.mojo.generation.loader.Reloadable
{
private static final long serialVersionUID = 1236612261692L;

  public MosquitoCollectionPointViewQueryBase(com.terraframe.mojo.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
  }

  public MosquitoCollectionPointViewQueryBase(com.terraframe.mojo.query.QueryFactory componentQueryFactory, com.terraframe.mojo.query.ViewQueryBuilder viewQueryBuilder)
  {
    super(componentQueryFactory, viewQueryBuilder);
  }
  public String getClassType()
  {
    return "csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView";
  }
  public com.terraframe.mojo.query.AttributeCharIF getCollectionId()
  {
    return getCollectionId(null);

  }
 
  public com.terraframe.mojo.query.AttributeCharIF getCollectionId(String alias)
  {
    return (com.terraframe.mojo.query.AttributeCharIF)this.getSelectable(csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView.COLLECTIONID, alias);

  }
 
  public csu.mrc.ivcc.mdss.entomology.CompositeMosquitoCollectionQuery.CompositeMosquitoCollectionQueryReferenceIF getCompositeCollection()
  {
    return getCompositeCollection(null);

  }
 
  public csu.mrc.ivcc.mdss.entomology.CompositeMosquitoCollectionQuery.CompositeMosquitoCollectionQueryReferenceIF getCompositeCollection(String alias)
  {

    return (csu.mrc.ivcc.mdss.entomology.CompositeMosquitoCollectionQuery.CompositeMosquitoCollectionQueryReferenceIF)this.getSelectable(csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView.COMPOSITECOLLECTION, alias);

  }
  public com.terraframe.mojo.query.AttributeMomentIF getDateCollected()
  {
    return getDateCollected(null);

  }
 
  public com.terraframe.mojo.query.AttributeMomentIF getDateCollected(String alias)
  {
    return (com.terraframe.mojo.query.AttributeMomentIF)this.getSelectable(csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView.DATECOLLECTED, alias);

  }
 
  public csu.mrc.ivcc.mdss.geo.generated.GeoEntityQuery.GeoEntityQueryReferenceIF getGeoEntity()
  {
    return getGeoEntity(null);

  }
 
  public csu.mrc.ivcc.mdss.geo.generated.GeoEntityQuery.GeoEntityQueryReferenceIF getGeoEntity(String alias)
  {

    return (csu.mrc.ivcc.mdss.geo.generated.GeoEntityQuery.GeoEntityQueryReferenceIF)this.getSelectable(csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView.GEOENTITY, alias);

  }
  public com.terraframe.mojo.query.AttributeCharIF getId()
  {
    return getId(null);

  }
 
  public com.terraframe.mojo.query.AttributeCharIF getId(String alias)
  {
    return (com.terraframe.mojo.query.AttributeCharIF)this.getSelectable(csu.mrc.ivcc.mdss.entomology.MosquitoCollectionPointView.ID, alias);

  }
 
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  @java.lang.SuppressWarnings("unchecked")
  public com.terraframe.mojo.query.OIterator<? extends MosquitoCollectionPointView> getIterator()
  {
    com.terraframe.mojo.query.ValueIterator valueIterator;
    if (_pageSize != null && _pageNumber != null)
    {
      valueIterator = (com.terraframe.mojo.query.ValueIterator<com.terraframe.mojo.dataaccess.ValueObject>)this.getComponentQuery().getIterator(_pageSize, _pageNumber);
    }
    else
    {
      valueIterator = (com.terraframe.mojo.query.ValueIterator<com.terraframe.mojo.dataaccess.ValueObject>)this.getComponentQuery().getIterator();
    }
    return new com.terraframe.mojo.query.ViewIterator<MosquitoCollectionPointView>(this.getMdClassIF(), valueIterator);
  }

}
