package csu.mrc.ivcc.mdss.entomology;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SexMaster.java
 *
 * @author Autogenerated by TerraFrame
 */
public abstract class SexMasterBase extends com.terraframe.mojo.system.EnumerationMaster implements com.terraframe.mojo.generation.loader.Reloadable
{
  public final static String CLASS = "csu.mrc.ivcc.mdss.entomology.SexMaster";
  private static final long serialVersionUID = 1236360375383L;
  
  public SexMasterBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static SexMasterQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    SexMasterQuery query = new SexMasterQuery(new com.terraframe.mojo.query.QueryFactory());
    com.terraframe.mojo.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static SexMaster get(String id)
  {
    return (SexMaster) com.terraframe.mojo.business.Business.get(id);
  }
  
  public static SexMaster getEnumeration(String enumName)
  {
    return (SexMaster) com.terraframe.mojo.business.Business.getEnumeration("csu.mrc.ivcc.mdss.entomology.SexMaster",enumName);
  }
  
  public static SexMaster lock(java.lang.String id)
  {
    SexMaster _instance = SexMaster.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static SexMaster unlock(java.lang.String id)
  {
    SexMaster _instance = SexMaster.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
